Missing setuptools depency
The run environment miss the following module, which is dependency from setuptools package. 
```
Traceback (most recent call last):
  File "/DATA/miniconda3/envs/vitables/bin/vitables", line 7, in <module>
    from vitables.start import gui
  File "/DATA/miniconda3/envs/vitables/lib/python3.9/site-packages/vitables/start.py", line 31, in <module>
    from vitables.vtapp import VTApp
  File "/DATA/miniconda3/envs/vitables/lib/python3.9/site-packages/vitables/vtapp.py", line 30, in <module>
    import tables
  File "/DATA/miniconda3/envs/vitables/lib/python3.9/site-packages/tables/__init__.py", line 73, in <module>
    from .tests import print_versions, test
  File "/DATA/miniconda3/envs/vitables/lib/python3.9/site-packages/tables/tests/__init__.py", line 21, in <module>
    from tables.tests.common import print_versions
  File "/DATA/miniconda3/envs/vitables/lib/python3.9/site-packages/tables/tests/common.py", line 25, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```